### ISSUE TITLE
Clarification wanted - no actual issue

### ISSUE THREAD

**Issue by MacKenzieRose** [MacKenzieRose/button-styles#1]
@thomasjbradley

I know how to fix the error I'm receiving (see below), but I'm wondering if our goal is to prioritize fewer lines of code, or if I should add a separate hover-styling section for .btn-ghost?

<img width="1060" alt="screen shot 2018-10-12 at 2 10 19 am" src="https://user-images.githubusercontent.com/19557909/46851005-08386d80-cdc4-11e8-8f92-3695c9fbc23b.png">

**Comment by thomasjbradley** [comment]
What you’ve done is perfect. Combining the two button styles together does make a lot of sense. And in a professional setting I’d likely use that solution.

But, and kind of funnily enough, you’re the first person who has ever noticed that those buttons have identical hover styles. So, I guess, I’m trying to hint to everybody else that they need to style the `:hover` state for every button.

Change it to duplicate the code a little bit, but know that you did it correctly.

**Comment by MacKenzieRose** [comment]
Okay; will make the necessary adjustments. Thank you :)
